# Generated by Django 4.2 on 2023-05-18 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "fullName",
                    models.CharField(
                        blank=True,
                        default="не указано",
                        max_length=50,
                        verbose_name="ФИО пользователя",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="не указано",
                        max_length=50,
                        verbose_name="email пользователя",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="не указано",
                        max_length=30,
                        verbose_name="номер телефона",
                    ),
                ),
                (
                    "deliveryType",
                    models.TextField(
                        blank=True,
                        default="ordinary",
                        max_length=30,
                        verbose_name="способ доставки",
                    ),
                ),
                (
                    "paymentType",
                    models.TextField(
                        blank=True,
                        default="online",
                        max_length=30,
                        verbose_name="способ оплаты",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        blank=True,
                        default="не указано",
                        max_length=30,
                        verbose_name="статус оплаты",
                    ),
                ),
                (
                    "city",
                    models.TextField(
                        blank=True,
                        default="не указано",
                        max_length=30,
                        verbose_name="город доставки",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        default="не указано",
                        max_length=30,
                        verbose_name="адрес доставки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0, verbose_name="номер счета")),
                ("name", models.TextField(default="не указан", max_length=30)),
                (
                    "month",
                    models.CharField(
                        max_length=2,
                        validators=[order.models.validate_month],
                        verbose_name="Месяц",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        max_length=2,
                        validators=[order.models.validate_year],
                        verbose_name="Год",
                    ),
                ),
                ("code", models.IntegerField(default=0, verbose_name="код оплаты")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="order.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежы",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="order.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент заказа",
                "verbose_name_plural": "Элементы заказа",
            },
        ),
    ]
